### ISSUE TITLE
Eclipse plugin installation issue

### ISSUE THREAD

**Issue by jitendrasbhati** [PLRI/arden2bytecode#3]
HI,

I have installed Arden4Eclipse plugin through market place in eclipse Juno/Kepler.
In eclipse, I clicked Windows->Preferences->ArdenSyntax->Compiler/Refactoring/Syntax Coloring/Templates, I got the same issue mentioned below:

Unable to create the selected preference page.
An error occurred while automatically activating bundle arden.xtext.ui (879).

Please suggest how to resolve this?

**Comment by Tetr4** [comment]
Hi, 

Sorry for the late answer, this project has been inactive for some time. 
At the moment the marketplace still links to the old version, which should be fixed soon. To install the current version **via the Eclipse Update Site** follow [these instructions](https://plri.github.io/arden2bytecode/arden4eclipse/#getting-started).
The new version fixes bugs with missing bundles and the preferences work on a fresh eclipse installation.
